version: '3'

services:
  web:
    build: .
    container_name: plm_web
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: plm_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plm
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  db_data:
